In [ ]:
# ex1
import numpy as np

ar = np.arange(0, 10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#ex2

my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list, dtype=int)
my_array


# array([3, 2, 0, 1, 2])

array([3, 2, 0, 1, 2])

In [89]:
#ex3

x = np.arange(1,10).reshape(3,3)
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
#ex4

s = np.random.rand(4,5)
s = np.around(s, decimals=2)
s

array([[0.84, 0.72, 0.99, 0.72, 0.47],
       [0.75, 0.53, 0.24, 0.99, 0.02],
       [0.34, 0.87, 0.47, 0.58, 0.94],
       [0.79, 0.06, 0.06, 0.31, 0.55]])

In [64]:
#ex5

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

array[1, :]


array([20, 21, 22, 23, 24])

In [112]:
#ex6

array = np.arange(0,10)
array[::-1]



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#EX7

identity_matrix = np.identity(4)
print(identity_matrix)



# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#ex8

a = np.arange(0,10)
print(f'Sum:{np.sum(a)}')
print(f'Average: {np.median(a)}')


Sum:45
Average: 4.5


In [141]:
#ex9

ar = np.arange(1,21).reshape(4,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [150]:
#ex10

a = np.arange(0,10)
a[a % 2 != 0]

array([1, 3, 5, 7, 9])